Pop window
Simpleshaikh1/MyMicroversePortfolio.github.io pull request #13
Opened 2023-04-18 09:51 UTC by Simpleshaikh1

I created a pop window that displays nav menu upon clicking hanburger. 

Upon clicking the links it navigates to the respective pages.

2023-04-18 09:54 UTC, amejid reviewed
Hi @Simpleshaikh1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failing linter check and does not have commits from your pair-programming partner. This is a collaborative activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 08:50 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @Simpleshaikh1 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that has a failing linters check, doesn't have the commits from your pair-programming partner and the commits you made are not verified. 
- Please make sure you make a commit on a verified Github account.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-19 10:54 UTC, mikethreels requested changes
Hi Toyyib, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- great job making the links to the specific parts of the page work.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 10:54 UTC, mikethreels commented on index.html
>                  </nav>
- [ ] please make sure that you pop-up window looks similar to the one in de figma template provided by Microverse:
Your project:
![afbeelding](https://user-images.githubusercontent.com/39240820/233052025-44558cc7-1c1a-4fa8-8500-b4a952310b29.png)
Figma template:
![afbeelding](https://user-images.githubusercontent.com/39240820/233052371-28e3e650-3359-488f-b600-17b9eed6d8a9.png)

2023-04-19 10:54 UTC, mikethreels commented on index.html
> +                    <div class="x-men"><span>X</span></div>
- [ ] when clicking on the "X" the menu pop-up doesn't close, it only closes when clicking on one of the links or just under the "X" please fix this.

2023-04-19 14:45 UTC, binhussen approved these changes
Hi @Simpleshaikh1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 15:01 UTC, merged